spring:
  application:
    name: accounts-service  # Identify this application
  cloud:
    config:
      uri: http://localhost:8888
      name: accounts-service
      profile: default

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port

management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

# Application info
info:
  app:
    name: Microservices Demo - Accounts Server
    description: This is a RESTful web service
    version: 1.0.0
